### ISSUE TITLE
RMextract 0.1 included in KERN

### ISSUE THREAD

**Issue by gijzelaerr** [lofar-astron/RMextract#12]
To quickly install losoto on Ubuntu 16.04 (LTS):

$ sudo apt-get install software-properties-common
$ sudo add-apt-repository -s ppa:kernsuite/kern-2
$ sudo apt-add-repository multiverse
$ sudo apt-get update
$ sudo apt-get install rmextract

more info about KERN:
http://kernsuite.info

metadata files can be found here:
https://github.com/kernsuite-debian/rmextract

**Comment by gmloose** [comment]
Both `LoSoTo` and `RMextract` can be installed directly from PyPI nowadys. I'm closing this issuue.
