### ISSUE TITLE
CODE filename case mismatch

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/RMextract#13]
While trying to download the IONEX files from ftp://ftp.aiub.unibe.ch/CODE/ I noticed a small mismatch between the file names. In my case, the getIONEX.py would try to download

    ftp://ftp.unibe.ch/aiub/CODE/2016/CODG0200.16i.Z
whereas the file name on the server is

    ftp://ftp.aiub.unibe.ch/CODE/2016/CODG0200.16I.Z
(16I instead of 16i) causing it to time out. I have fixed it for myself by modifying lines 417-419 of getIONEX.py, but I'm not sure if this breaks something else perhaps.

Cheers,

Frits

**Comment by maaijke** [comment]
I added specific path for unibe server now,please test.

**Comment by twillis449** [comment]
@maaijke I thought you had changed all references of  ftp.unibe.ch  to ftp.aiub.unibe.ch last September or some such similar date. But I guess there was still one reference lurking around. :(

**Comment by maaijke** [comment]
I assume Fritshas  put in the server name himself by hand. The default server is indeed different and also has the CODG data.

**Comment by tikk3r** [comment]
Sorry for the delayed response.
The default server (ftp://ftp.unibe.ch/aiub/CODE/2016/) isn't reachable for me. The assumption they just changed the position of the "aiub" part led me to the other one.
I have just tested the new code and it works fine with the other server now.

**Comment by gmloose** [comment]
I guess this is no longer relevant. Recently, several servers have been updated (see https://github.com/lofar-astron/RMextract/pull/48). I'm closing this issue.
