### ISSUE TITLE
Problem reading ROBR file

### ISSUE THREAD

**Issue by darafferty** [lofar-astron/RMextract#21]
When running getRM.getRM() with server="ftp://gnss.oma.be/gnss/products/IONEX/" and prefix="ROBR", I get the error "could not broadcast input array from shape (6) into shape (0)". This problem seems to be caused by this line in the downloaded file that is not processed correctly:
`
'  2018    11     1     0    15     0                        EPOCH OF CURRENT MAP\n'
`

I'm not sure though if ROBR files are officially supported or not...

**Comment by maaijke** [comment]
I missed a "END OF TEC MAP" when combining all the ROBR maps of one day. You need to delete the old ROBR data to make this work
