### ISSUE TITLE
RMextract fails for years < 2010

### ISSUE THREAD

**Issue by twillis449** [lofar-astron/RMextract#22]
Hi Maaijke

In the version of RMextract that I'm using, if I specify a year < 2010 (say 2009) RMextract forms the codg request as e.g. codg3350.9i.Z instead of codg3350.09i.Z so somewhere in your formatting you are clipping off all leading zeros. Of course this causes RMextract not to return any file.:( 

Reason for looking this far back in time is that  the  GMIMS team has asked me to compare the ionosphere RMs determined by RMextract with those they derived by using the simpler International Reference Ionosphere (IRI) for observations they did in 2006 - 2009. The referee for a paper they submitted told them to do this comparison.

Cheers

Tony

**Comment by maaijke** [comment]
which version of RMextract are you using? and which server? It seems to work fine for me.

**Comment by twillis449** [comment]
Hi Maaijke

I upgraded to RMextract V0.3, and you are correct- looks like the file specification is correct there. :)

Tony
