### ISSUE TITLE
Python 3.12: ModuleNotFoundError: No module named 'numpy.distutils'

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/RMextract#53]
Just reporting. This shows up when trying to install:
> ModuleNotFoundError: No module named 'numpy.distutils'

Explanation: https://stackoverflow.com/a/77284076/6764984.

**Comment by gmloose** [comment]
Thanks for reporting. Looks like there's still some work to do to make RMextract Python 3.12 compatible.

**Comment by gmloose** [comment]
Solved by https://github.com/lofar-astron/RMextract/pull/55
