### ISSUE TITLE
unreleased

### ISSUE THREAD

**Issue by gijzelaerr** [lofar-astron/RMextract#7]
Hi!

I am in the process of packaging up 'prefactor':

https://github.com/lofar-astron/prefactor

It will become a debian package and included in the KERN suite:

http://kernsuite.info/

prefactor depends on RMextract. I noticed RMextract doesn't have an official release (yet). Can you be so kind to press the release button? Just having a 0.1 tag on github already makes the packaging procedure much easier an then everybody is sure that no versions are mixed.

Let me know if you have any questions or problems :)

thanks!

**Comment by tammojan** [comment]
Maaijke released https://github.com/lofar-astron/RMextract/releases/tag/v0.1 .
